# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/menao/Project_Test/fpga/cs256_project.srcs/sources_1/ip/char_ROM_diag/char_ROM_diag.xci
# IP: The module: 'char_ROM_diag' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/menao/Project_Test/fpga/cs256_project.gen/sources_1/ip/char_ROM_diag/char_ROM_diag_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_ROM_diag'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/menao/Project_Test/fpga/cs256_project.srcs/sources_1/ip/char_ROM_diag/char_ROM_diag.xci
# IP: The module: 'char_ROM_diag' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/menao/Project_Test/fpga/cs256_project.gen/sources_1/ip/char_ROM_diag/char_ROM_diag_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_ROM_diag'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
